---
title: "Thematic Mapping with Simple Features"
output: html_document
---
&nbsp;

## Simple Features

The initial sections of *Mapping in R** introduced you to plotting latitude and longitude on an interactive map (`leaflet`), and generating a thematic map using `tidycensus.`  A good next step is to learn how to make other customized thematic maps with some more useful packages: `tmap`, `sf`, `ggplot2` (using ggplot::geom_sf).  

**The backbone of this type of mapping data manipulation is the `sf` package** -- sf for simple features -- which is a modern tidyverse compatible package for encoding spatial vector data.  We learn more about `sf` and `sp` during the workshop.  You can review the video if you want to hear the discussion.  Or check the slides \*\*\*jrl\*\*\*.


First let's introduce the `tmap` package which you'll see is an easy to use package that builds spatial distributions on geographic maps.



## Sections

1. [basic thematic mapping](031_thematic_mapping.html): creating choropleth's with `tmap`

1. [interactive thematic mapping](033_thematic_leaflet_example.html) with leaflet

1. [Sharing ouput files](036_thematic_mapping-outputs-fullwebpage.html): saving maps.

## Hands-on

Head over to the [exercises section] and try to make your own thematic map.

